apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qr-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /qr
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.servicenode.name }}
            port:
              number: {{ .Values.servicenode.port }}
