# Workflow Name
name: "ArgoCD Workflow"

# Workflow Triggers
on:
  workflow_dispatch: # Enables manual trigger for destroy job

# Environment Variables
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: ${{ vars.S3_BUCKET_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER: ${{ vars.EKS_CLUSTER }}

# Define Jobs
jobs:
  terraform:
    name: "Deploy Infra with Terraform on AWS"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.7/2024-12-12/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl  # Download and install kubectl CLI
      
      - name: Get Kubernetes config
        id: getconfig
        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER }} --region ${{ vars.AWS_REGION }}

      - name: Installing Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      - name: Install Ingress controller
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade -i ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx --create-namespace \
          --set controller.service.type=LoadBalancer \
          --reuse-values \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol"="tcp" \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-cross-zone-load-balancing-enabled"="true" \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-nlb-target-type"="instance" \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-scheme"="internet-facing" \

      - run: kubectl get pods -n ingress-nginx
      
      - run: kubectl get svc -n ingress-nginx


      - name: Install htpasswd for password generation
        run: sudo apt-get update && sudo apt-get install -y apache2-utils

      - name: Installing ArgoCD
        env:
          ARGOCD_ADMIN_PASSWORD: ${{ secrets.ARGOCD_ADMIN_PASSWORD }}
        run: |
          PASSWORD_HASH=$(htpasswd -nbB admin "$ARGOCD_ADMIN_PASSWORD" | cut -d: -f2)
          helm repo add argo https://argoproj.github.io/argo-helm
          helm upgrade -i argocd argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          --set configs.secret.argocdServerAdminPassword="$PASSWORD_HASH" \
          --set server.service.type=ClusterIP \
          --set configs.params."server\.insecure"=true \
          --set server.ingress.enabled=true \
          --set server.ingress.class=nginx \
           
      - run: kubectl get pods -n argocd
      - run: kubectl get svc -n argocd
      - run: kubectl get ingress -n argocd
