name: Building QR generator images

on: 
  workflow_dispatch:

jobs:
  buildapi:

    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: 'api/requirements.txt'
      
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install --no-cache-dir -r api/requirements.txt
      - name: Test with pytest
        run: pytest api/test_main.py        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sabryp3/qr-generator:api-latest
          file: api/Dockerfile

  buildnode:

    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          # Semantic version range syntax or exact version of a Node.js version
          node-version: 24
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'npm'
          cache-dependency-path: 'front-end-nextjs/package-lock.json'
      - run: npm ci
        working-directory: front-end-nextjs
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sabryp3/qr-generator:nodejs-latest
          file: front-end-nextjs/Dockerfile
          context: front-end-nextjs 
